name: Release Windows App

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: windows-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            core.setOutput("release_id", data.id)
            return data.id
        outputs:
          release_id: ${{ steps.create-release.outputs.result }}
      - name: Debug release id
        run: echo "Release ID is ${{ needs.create-release.outputs.release_id }}"

  build-windows:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: x86_64
            rust_target: x86_64-pc-windows-msvc
            artifact_arch: x64
            os: windows-latest

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "yarn"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.rust_target }}

      - name: Install frontend dependencies
        run: yarn install

      - name: Get package version
        run: |
          node -e "console.log('PACKAGE_VERSION=' + require('./src-tauri/tauri.conf.json').package.version)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Update tauri config
        run: |
          bash ./update_tauri_config.sh --mode release
        shell: bash

      - name: Download host_server, uv, bun binaries
        run: bash .github/scripts/download-bin.sh ${{ matrix.config.arch }} ${{ matrix.config.os }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash

      - name: Inject environment variables
        run: |
          echo "NPM_CONFIG_REGISTRY=${{ secrets.NPM_CONFIG_REGISTRY }}" | Out-File -FilePath src-tauri/bin/.env -Encoding utf8
          Add-Content src-tauri/bin/.env "UV_INDEX=${{ secrets.UV_INDEX }}"
          Add-Content src-tauri/bin/.env "UV_DEFAULT_INDEX=${{ secrets.UV_DEFAULT_INDEX }}"
          Add-Content src-tauri/bin/.env "UV_EXTRA_INDEX_URL=${{ secrets.UV_EXTRA_INDEX_URL }}"
        shell: pwsh
      - name: List src-tauri folder contents
        run: |
          echo "📂 src-tauri 文件夹内容:"
          dir src-tauri

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          args: --target ${{ matrix.config.rust_target }}

      - name: List build artifacts
        run: Get-ChildItem -Recurse src-tauri/target
        shell: pwsh
  publish-release:
    permissions:
      contents: write
    runs-on: windows-latest
    needs: [create-release, build-windows]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
